name: pnta_flutter
description: "Official PNTA Flutter plugin to make push notifications suck less."
version: 1.1.1
homepage: https://pnta.io
repository: https://github.com/pnta-io/pnta-flutter-plugin
documentation: https://docs.pnta.io

topics:
    - notifications
    - push
    - fcm
    - apns

environment:
    sdk: ^3.6.1
    flutter: ">=3.3.0"

dependencies:
    flutter:
        sdk: flutter
    plugin_platform_interface: ^2.0.2
    url_launcher: ^6.2.5

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0

flutter:
    plugin:
        platforms:
            android:
                package: io.pnta.pnta_flutter
                pluginClass: PntaFlutterPlugin
            ios:
                pluginClass: PntaFlutterPlugin
