name: pnta_flutter
description: "Official PNTA Flutter plugin to make push notifications suck less."
version: 0.0.1
homepage: https://pnta.io
repository: https://github.com/pntaio/pnta_flutter

environment:
    sdk: ^3.6.1
    flutter: ">=3.3.0"

dependencies:
    flutter:
        sdk: flutter
    plugin_platform_interface: ^2.0.2

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0

flutter:
    plugin:
        platforms:
            android:
                package: io.pnta.pnta_flutter
                pluginClass: PntaFlutterPlugin
            ios:
                pluginClass: PntaFlutterPlugin
